Fix LLVM build for GCC 14, and for windows
The `-femulated-tls` is to fix the error:
```
/opt/host-x86_64-w64-mingw32/clang/bin/x86_64-w64-mingw32-ld:
lib/libLLVMSupport.a(BalancedPartitioning.cpp.obj):BalancedPartitioni:(.text$_ZNSt13__future_base13_State
_baseV213_M_set_resultESt8functionIFSt10unique_ptrINS_12_Result_baseENS3_8_DeleterEEvEEb[_ZNSt13__future_base13_State_baseV213_M_set_resultESt8functionIFSt10unique_ptr
INS_12_Result_baseENS3_8_DeleterEEvEEb]+0x82): undefined reference to
`std::__once_callable'
```

The `libcxx` changes are to fix building for mingw, as there's symbol
resolution issues if we don't use `lld` or try to make too many things
shared instead of static.